library verilog;
use verilog.vl_types.all;
entity DE0_TOP is
    port(
        CLOCK_50        : in     vl_logic;
        CLOCK_50_2      : in     vl_logic;
        BUTTON          : in     vl_logic_vector(2 downto 0);
        SW              : in     vl_logic_vector(9 downto 0);
        HEX0_D          : out    vl_logic_vector(6 downto 0);
        HEX0_DP         : out    vl_logic;
        HEX1_D          : out    vl_logic_vector(6 downto 0);
        HEX1_DP         : out    vl_logic;
        HEX2_D          : out    vl_logic_vector(6 downto 0);
        HEX2_DP         : out    vl_logic;
        HEX3_D          : out    vl_logic_vector(6 downto 0);
        HEX3_DP         : out    vl_logic;
        LEDG            : out    vl_logic_vector(9 downto 0);
        UART_TXD        : out    vl_logic;
        UART_RXD        : in     vl_logic;
        UART_CTS        : out    vl_logic;
        UART_RTS        : in     vl_logic;
        DRAM_DQ         : inout  vl_logic_vector(15 downto 0);
        DRAM_ADDR       : out    vl_logic_vector(12 downto 0);
        DRAM_LDQM       : out    vl_logic;
        DRAM_UDQM       : out    vl_logic;
        DRAM_WE_N       : out    vl_logic;
        DRAM_CAS_N      : out    vl_logic;
        DRAM_RAS_N      : out    vl_logic;
        DRAM_CS_N       : out    vl_logic;
        DRAM_BA_0       : out    vl_logic;
        DRAM_BA_1       : out    vl_logic;
        DRAM_CLK        : out    vl_logic;
        DRAM_CKE        : out    vl_logic;
        FL_DQ           : inout  vl_logic_vector(14 downto 0);
        FL_DQ15_AM1     : inout  vl_logic;
        FL_ADDR         : out    vl_logic_vector(21 downto 0);
        FL_WE_N         : out    vl_logic;
        FL_RST_N        : out    vl_logic;
        FL_OE_N         : out    vl_logic;
        FL_CE_N         : out    vl_logic;
        FL_WP_N         : out    vl_logic;
        FL_BYTE_N       : out    vl_logic;
        FL_RY           : in     vl_logic;
        LCD_BLON        : out    vl_logic;
        LCD_RW          : out    vl_logic;
        LCD_EN          : out    vl_logic;
        LCD_RS          : out    vl_logic;
        LCD_DATA        : inout  vl_logic_vector(7 downto 0);
        SD_DAT0         : inout  vl_logic;
        SD_DAT3         : inout  vl_logic;
        SD_CMD          : inout  vl_logic;
        SD_CLK          : out    vl_logic;
        SD_WP_N         : in     vl_logic;
        PS2_KBDAT       : inout  vl_logic;
        PS2_KBCLK       : inout  vl_logic;
        PS2_MSDAT       : inout  vl_logic;
        PS2_MSCLK       : inout  vl_logic;
        VGA_HS          : out    vl_logic;
        VGA_VS          : out    vl_logic;
        VGA_R           : out    vl_logic_vector(3 downto 0);
        VGA_G           : out    vl_logic_vector(3 downto 0);
        VGA_B           : out    vl_logic_vector(3 downto 0);
        GPIO0_CLKIN     : in     vl_logic_vector(1 downto 0);
        GPIO0_CLKOUT    : out    vl_logic_vector(1 downto 0);
        GPIO0_D         : inout  vl_logic_vector(31 downto 0);
        GPIO1_CLKIN     : in     vl_logic_vector(1 downto 0);
        GPIO1_CLKOUT    : out    vl_logic_vector(1 downto 0);
        GPIO1_D         : inout  vl_logic_vector(31 downto 0)
    );
end DE0_TOP;
